# -*- coding: utf-8 -*-
"""qwen cho final jsonl

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Wcemgn8AVcF4JTsKJPHDY_RLH3-qv97
"""

import json
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from rouge import Rouge


class PremiumRAGInference:
    def __init__(self, model_name="Qwen/Qwen2.5-3B-Instruct"):
        print("=== Loading Qwen RAG Inference System ===")

        bnb_config = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_quant_type="nf4",
            bnb_4bit_compute_dtype=torch.float16,
        )

        self.tokenizer = AutoTokenizer.from_pretrained(model_name)

        self.llm = AutoModelForCausalLM.from_pretrained(
            model_name,
            quantization_config=bnb_config,
            device_map="auto"
        )

        self.rouge = Rouge()

        self.SYSTEM_PROMPT = """
Bạn là trợ giảng AI chuyên về NLP và Machine Learning.

QUY TẮC:
- Chỉ trả lời dựa trên NGUỒN được cung cấp
- Nếu thiếu thông tin: nói rõ
- Giải thích dễ hiểu cho sinh viên
- Trích dẫn [1], [2], ...

Trả lời bằng tiếng Việt.
"""

    def load_final_context(self, file_path):
        """
        Load final_context.jsonl
        """
        data = []

        with open(file_path, "r", encoding="utf-8") as f:
            for line in f:
                data.append(json.loads(line))

        return data

    def build_prompt(self, query, contexts):
        """
        Build prompt chuẩn cho Qwen
        """
        source_text = "\n\n".join(
            [f"[{i+1}] {ctx}" for i, ctx in enumerate(contexts)]
        )

        prompt = f"""
{self.SYSTEM_PROMPT}

NGUỒN:
{source_text}

CÂU HỎI:
{query}

TRẢ LỜI:
"""
        return prompt

    def generate_answer(self, query, contexts):
        prompt = self.build_prompt(query, contexts)

        inputs = self.tokenizer(
            prompt,
            return_tensors="pt",
            truncation=True,
            max_length=4096
        ).to(self.llm.device)

        with torch.no_grad():
            outputs = self.llm.generate(
                **inputs,
                max_new_tokens=512,
                temperature=0.1,
                do_sample=True,            # was False — caused temperature=0.1 to be ignored
                repetition_penalty=1.1
            )

        answer = self.tokenizer.decode(
            outputs[0][inputs.input_ids.shape[-1]:],
            skip_special_tokens=True
        )

        return answer.strip()

    def evaluate(self, answer, ground_truth):
        rouge_score = self.rouge.get_scores(answer, ground_truth)[0]

        return {
            "ROUGE-1": round(rouge_score["rouge-1"]["f"], 4),
            "ROUGE-2": round(rouge_score["rouge-2"]["f"], 4),
            "ROUGE-L": round(rouge_score["rouge-l"]["f"], 4)
        }


if __name__ == "__main__":
    rag = PremiumRAGInference()

    dataset = rag.load_final_context("final_context.jsonl")

    print("=== RAG Chatbot Ready ===")

    while True:
        query = input("\nNhập câu hỏi (gõ 'exit' để thoát): ")

        if query.lower() == "exit":
            break

        # demo: lấy context đầu tiên
        contexts = dataset[0]["contexts"]

        print("\nĐang suy nghĩ...\n")

        answer = rag.generate_answer(query, contexts)

        print("=" * 80)
        print("ANSWER:")
        print(answer)