# -*- coding: utf-8 -*-
"""context_to_jsonl

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yEu3NnR9hDLc7K2TDfjflzgWZdDu3a_S
"""

# context_to_jsonl.py

import json
import re
from collections import defaultdict


FILLERS = [
    "okay",
    "right",
    "you know",
    "kind of",
    "sort of",
    "basically",
    "actually",
    "uh",
    "um",
    "AUDIO OUT",
]


def clean_text(text: str) -> str:
    """
    Clean transcript artifacts.
    """

    if not text:
        return ""

    text = text.replace("\n", " ")

    # remove fillers
    for filler in FILLERS:
        text = re.sub(
            rf"\b{re.escape(filler)}\b",
            "",
            text,
            flags=re.IGNORECASE,
        )

    # remove repeated words
    text = re.sub(r"\b(\w+)( \1\b)+", r"\1", text)

    # normalize spaces
    text = re.sub(r"\s+", " ", text)

    return text.strip()


def group_docs_by_video(final_docs):
    """
    Group retrieved chunks by video_id/source.
    """

    grouped = defaultdict(list)

    for doc in final_docs:
        video_id = doc.metadata.get("video_id", "unknown")

        grouped[video_id].append(doc)

    return grouped


def merge_grouped_docs(grouped_docs):
    """
    Merge chunks from same source/video.
    """

    merged_results = []

    for video_id, docs in grouped_docs.items():

        # sort by start time
        docs = sorted(
            docs,
            key=lambda d: d.metadata.get("start_time", 0)
        )

        merged_text = []

        for doc in docs:
            cleaned = clean_text(doc.page_content)

            if cleaned:
                merged_text.append(cleaned)

        final_text = " ".join(merged_text)

        first_doc = docs[0]

        merged_results.append({
            "video_id": video_id,
            "title": first_doc.metadata.get("title"),
            "course": first_doc.metadata.get("course"),
            "url": first_doc.metadata.get("url"),

            "chunks_used": len(docs),

            "context": final_text
        })

    return merged_results


def save_jsonl(data, output_path="final_context.jsonl"):
    """
    Save merged contexts to jsonl.
    """

    with open(output_path, "w", encoding="utf-8") as f:

        for item in data:
            f.write(
                json.dumps(item, ensure_ascii=False)
                + "\n"
            )

    print(f"\nSaved to: {output_path}")
    print(f"Total contexts: {len(data)}")


def build_final_jsonl(final_docs,
                      output_path="final_context.jsonl"):
    """
    Full pipeline:
    docs -> group -> merge -> clean -> jsonl
    """

    grouped = group_docs_by_video(final_docs)

    merged = merge_grouped_docs(grouped)

    save_jsonl(merged, output_path)

    return merged